server:
  port: 8089

#cn.bugstack.reade.forum.

spring:
#  指定应用的名称，，在spring cloud中被用来注册的服务名。
#  application:
#    name: reade-forum
  # 指定读取 yml 配置文件
  profiles:
    active: local

kafka:
  bootstrap:
    servers: 192.168.202.131:9092
  servers:
    first:
      topic: "first_topic"
      group: "first_group"