spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jk_manage?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 1959337028@qq.com
    password: sjtvybcgmzaobiad
    port: 465
    properties:
      from: 1959337028@qq.com
#      本地redis
  redis:
    host: localhost
    port: 6379
    database: 0

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
#    开启驼峰命名
    map-underscore-to-camel-case: true

#控制打印sql
logging:
  level:
#    cn.bugstack.reade.forum.infrastructure.mapper 是 放置 mapper 的包名
    cn.bugstack.reade.forum.infrastructure.mapper: debug
